export const phoneData = [
  // {
  //   id: 1,
  //   name: "Xiomi Redmi Note 10S",
  //   img: "/img/products/redmi/redmi-note-10s.jpeg",
  //   desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  //   price: 2643000,
  // },
  {
    id: 2,
    name: "Apple iPhone 13 Pro 128 GB Blue/Green",
    img: "/img/products/iphone/13-pro-blue-128gb_1.jpg",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    price: 1210,
    category: "Smartfon",
    brand: "iPhone",
  },
  {
    id: 3,
    name: "Apple iPhone 13 Pro 128 GB Gold/Silver/Gray",
    img: "/img/products/iphone/13-pro-gold-128gb_1.jpeg",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    price: 1200,
    category: "Smartfon",
    brand: "iPhone",
  },
  {
    id: 4,
    name: "Apple iPhone 13 Pro 256 GB Gray/Gold/Silver",
    img: "/img/products/iphone/13-pro-gold-256gb_1.jpeg",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    price: 1320,
    category: "Smartfon",
    brand: "iPhone",
  },
  {
    id: 5,
    name: "Apple iPhone 13 Pro 256 GB Green/Blue",
    img: "/img/products/iphone/13-pro-green-256gb_1.jpeg",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    price: 1340,
    category: "Smartfon",
    brand: "iPhone",
  },
  {
    id: 6,
    name: "Apple iPhone 13 Pro Max 128 GB Blue/Green/Grey",
    img: "/img/products/iphone/13-promax-blue-128gb_1.jpeg",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    price: 1330,
    category: "Smartfon",
    brand: "iPhone",
  },
  {
    id: 7,
    name: "Apple iPhone 13 Pro Max 128 GB Gold/Silver",
    img: "/img/products/iphone/13-promax-silver-128gb_1.jpeg",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    price: 1320,
    category: "Smartfon",
    brand: "iPhone",
  },
  {
    id: 8,
    name: "Apple iPhone 13 Pro Max 256 GB Grey/Gold/Silver",
    img: "/img/products/iphone/13-promax-silver-grey-gold-256gb_1.jpeg",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    price: 1420,
    category: "Smartfon",
    brand: "iPhone",
  },
  {
    id: 9,
    name: "Apple iPhone 13 Pro Max 256 GB Blue",
    img: "/img/products/iphone/13-promax-blue-256gb_1.jpeg",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    price: 1430,
    category: "Smartfon",
    brand: "iPhone",
  },
  {
    id: 10,
    name: "Apple iPhone 13 Pro Max 256 GB Green",
    img: "/img/products/iphone/13-promax-green-256gb_1.jpg",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    price: 1430,
    category: "Smartfon",
    brand: "iPhone",
  },
];
